### Installing Libraries

In [ ]:
!pip install PyPDF2
!pip install pdfplumber
!pip install sentence-transformers nltk

Collecting PyPDF2
  Downloading pypdf2-3.0.1-py3-none-any.whl.metadata (6.8 kB)
Downloading pypdf2-3.0.1-py3-none-any.whl (232 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.6/232.6 kB 4.0 MB/s eta 0:00:00
Installing collected packages: PyPDF2
Successfully installed PyPDF2-3.0.1
Collecting pdfplumber
  Downloading pdfplumber-0.11.7-py3-none-any.whl.metadata (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.8/42.8 kB 1.2 MB/s eta 0:00:00
Collecting pdfminer.six==20250506 (from pdfplumber)
  Downloading pdfminer_six-20250506-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: Pillow>=9.1 in /usr/local/lib/python3.11/dist-packages (from pdfplumber) (11.2.1)
Collecting pypdfium2>=4.18.0 (from pdfplumber)
  Downloading pypdfium2-4.30.1-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.2/48.2 kB 2.2 MB/s eta 0:00:00
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from pdfminer.six==20250506->pdfplumber) (3.4.2)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.11/dist-packages (from pdfminer.six==20250506->pdfplumber) (43.0.3)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.11/dist-packages (from cryptography>=36.0.0->pdfminer.six==20250506->pdfplumber) (1.17.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20250506->pdfplumber) (2.22)
Downloading pdfplumber-0.11.7-py3-none-any.whl (60 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 kB 4.7 MB/s eta 0:00:00
Downloading pdfminer_six-20250506-py3-none-any.whl (5.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 35.0 MB/s eta 0:00:00
Downloading pypdfium2-4.30.1-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 24.9 MB/s eta 0:00:00
Installing collected packages: pypdfium2, pdfminer.six, pdfplumber
Successfully installed pdfminer.six-20250506 pdfplumber-0.11.7 pypdfium2-4.30.1
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.11/dist-packages (4.1.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.11/dist-packages (3.9.1)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (4.52.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (4.67.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (2.6.0+cu124)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (1.15.3)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (0.33.0)
Requirement already satisfied: Pillow in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (11.2.1)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.11/dist-packages (from sentence-transformers) (4.14.0)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from nltk) (1.5.1)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.11/dist-packages (from nltk) (2024.11.6)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.3.2)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2.32.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.1.5)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch>=1.11.0->sentence-transformers)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence-transformers) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2.0.2)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.21.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2025.6.15)
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 3.5 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 102.1 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 69.8 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 40.8 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.0 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 6.2 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 15.6 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.6 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.9 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 68.5 MB/s eta 0:00:00
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
Successfully installed nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127

In [ ]:
import os
import json
from google.colab import userdata
from google.colab import drive
import pdfplumber
from operator import itemgetter
from pathlib import Path
import PyPDF2
import pandas as pd
import openai
import numpy as np

### Mounting Drive

In [ ]:
drive.mount('/content/drive')

Mounted at /content/drive

### Changing Directory

In [ ]:
os.chdir('/content/drive/MyDrive/GenAI_Course_Master/HelpMate_AI')

In [ ]:
print("Current Dir - ", os.getcwd())

Current Dir -  /content/drive/MyDrive/GenAI_Course_Master/HelpMate_AI

In [ ]:
!find /content/drive -name "HelpMate_AI.ipynb"

/content/drive/MyDrive/GenAI_Course_Master/HelpMate_AI/HelpMate_AI.ipynb

In [ ]:
!ls

'Copy of HelpMate_AI'   Principal-Sample-Life-Insurance-Policy.pdf
 HelpMate_AI.ipynb

### Adding OpenAI Key

In [ ]:
api_key = userdata.get('OpenAI')

### Code to Chunk and Embed PDF using SentenceTransformers

#### Extracting Text From PDF

In [ ]:
pdf_path = Path('/content/drive/MyDrive/GenAI_Course_Master/HelpMate_AI/Principal-Sample-Life-Insurance-Policy.pdf')

In [ ]:
pdf_path

PosixPath('/content/drive/MyDrive/GenAI_Course_Master/HelpMate_AI/Principal-Sample-Life-Insurance-Policy.pdf')

In [ ]:
# Function to check whether a word is present in a table or not for segregation of regular text and tables
def check_bboxes(word, table_bbox):
    # Check whether word is inside a table bbox.
    l = word['x0'], word['top'], word['x1'], word['bottom']
    r = table_bbox
    return l[0] > r[0] and l[1] > r[1] and l[2] < r[2] and l[3] < r[3]

In [ ]:
def extract_text_from_pdf(pdf_path):
    extracted_data = []
    with open(pdf_path, 'rb') as file:
        pdf_reader = PyPDF2.PdfReader(file)
        for i, page in enumerate(pdf_reader.pages):
            text = page.extract_text()
            extracted_data.append([i + 1, text if text else ""])
    return extracted_data

In [ ]:
# Function to Extract text from PDF
def extract_text_from_pdf2(pdf_path):
    p = 0               # Storing the iteration loop storing page number depending on the text
    full_text = []      # A empty list to "full_text" to store all the text files

    with pdfplumber.open(pdf_path) as pdf:
      for page in pdf.pages:
        page_no = f"Page {p+1}"
        text = page.extract_text()

        tables = page.find_tables()
        table_bboxes = [i.bbox for i in tables]
        tables = [{'table': i.extract(), 'top':i.bbox[1]} for i in tables]
        non_table_words = [word for word in page.extract_words() if not any([check_bboxes(word, table_bbox) for table_bbox in table_bboxes])]
        lines = []

        for cluster in pdfplumber.utils.cluster_objects(non_table_words + tables, itemgetter('top'), tolerance = 5):
          if 'text' in cluster[0]:
            try:
              lines.append(' '.join([word['text'] for word in cluster]))
            except KeyError:
              pass
          elif 'table' in cluster[0]:
            lines.append(json.dumps(cluster[0]['table']))
        cleaned_text = ' '.join(filter(None, lines)).strip()
        full_text.append([page_no, cleaned_text])
        p += 1
    return full_text

In [ ]:
# Process the PDF
print(f"...Processing {pdf_path.name}")

...Processing Principal-Sample-Life-Insurance-Policy.pdf

#### Chunking Text for better embedding

In [ ]:
import nltk
nltk.download('punkt')
from nltk.tokenize import sent_tokenize

def chunk_text(text_input, chunk_size=500, overlap=50, strategy="sliding"):
    """
    Chunk long text into smaller pieces for embedding.

    Parameters:
        text_input: str or List[str] — The input text or list of texts (e.g. from pages)
        chunk_size: int — Max number of words per chunk
        overlap: int — Number of overlapping words between chunks
        strategy: str — 'sliding' or 'sentence'

    Returns:
        List[str] — Chunked text pieces
    """
    chunks = []

    # Combine if list of strings
    if isinstance(text_input, list):
        text = " ".join(text_input)
    else:
        text = text_input

    if strategy == "sliding":
        words = text.split()
        for i in range(0, len(words), chunk_size - overlap):
            chunk = " ".join(words[i:i + chunk_size])
            chunks.append(chunk)

    elif strategy == "sentence":
        sentences = sent_tokenize(text)
        current_chunk = ""
        for sentence in sentences:
            if len(current_chunk.split()) + len(sentence.split()) <= chunk_size:
                current_chunk += " " + sentence
            else:
                chunks.append(current_chunk.strip())
                current_chunk = sentence
        if current_chunk:
            chunks.append(current_chunk.strip())

    else:
        raise ValueError("Invalid strategy. Choose 'sliding' or 'sentence'.")

    return chunks

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

In [ ]:
# 1. Extract text (including tables) from the PDF
extracted_text = extract_text_from_pdf(pdf_path)

# 2. Convert the extracted data into a DataFrame
extracted_text_df = pd.DataFrame(extracted_text, columns=['Page No.', 'Page_Text'])

# 3. Add a column for the document name
extracted_text_df['Document Name'] = Path(pdf_path).name

# 4. Append to a list (if you plan to process multiple PDFs)
data = []
data.append(extracted_text_df)

# 5. Display confirmation and preview
print(f"✅ Finished processing {pdf_path}")
print(extracted_text_df.head())  # Show first 5 rows

✅ Finished processing /content/drive/MyDrive/GenAI_Course_Master/HelpMate_AI/Principal-Sample-Life-Insurance-Policy.pdf
   Page No.                                          Page_Text  \
0         1   \n  \n \n \nGROUP POLICY FOR:  \nRHODE ISLAND...
1         2   \n \n \n  \n \n \n \n  \n \n \n \n   \n \n \n...
2         3   \n \n \n  \n  \nGC 806 VAL   \n POLICY RIDER ...
3         4   \n \n \n  \n \n                     \nThis pa...
4         5   \n \n \nThis policy has been updated effectiv...

                                Document Name
0  Principal-Sample-Life-Insurance-Policy.pdf
1  Principal-Sample-Life-Insurance-Policy.pdf
2  Principal-Sample-Life-Insurance-Policy.pdf
3  Principal-Sample-Life-Insurance-Policy.pdf
4  Principal-Sample-Life-Insurance-Policy.pdf

In [ ]:
# 1. Extract text (including tables) from the PDF
extracted_text = extract_text_from_pdf2(pdf_path)

# 2. Convert the extracted data into a DataFrame
extracted_text_df = pd.DataFrame(extracted_text, columns=['Page No.', 'Page_Text'])

# 3. Add a column for the document name
extracted_text_df['Document Name'] = Path(pdf_path).name

# 4. Append to a list (if you plan to process multiple PDFs)
data = []
data.append(extracted_text_df)

# 5. Display confirmation and preview
print(f"✅ Finished processing {pdf_path}")
print(extracted_text_df.head())  # Show first 5 rows

✅ Finished processing /content/drive/MyDrive/GenAI_Course_Master/HelpMate_AI/Principal-Sample-Life-Insurance-Policy.pdf
  Page No.                                          Page_Text  \
0   Page 1  DOROTHEA GLAUSE S655 RHODE ISLAND JOHN DOE 01/...
1   Page 2                 This page left blank intentionally
2   Page 3  POLICY RIDER GROUP INSURANCE POLICY NO: S655 C...
3   Page 4                 This page left blank intentionally
4   Page 5  PRINCIPAL LIFE INSURANCE COMPANY (called The P...

                                Document Name
0  Principal-Sample-Life-Insurance-Policy.pdf
1  Principal-Sample-Life-Insurance-Policy.pdf
2  Principal-Sample-Life-Insurance-Policy.pdf
3  Principal-Sample-Life-Insurance-Policy.pdf
4  Principal-Sample-Life-Insurance-Policy.pdf

In [ ]:
insurance_pdf_data = pd.concat(data, ignore_index=True)

In [ ]:
insurance_pdf_data.head()

,Page No.,Page_Text,Document Name
0,Page 1,DOROTHEA GLAUSE S655 RHODE ISLAND JOHN DOE 01/...,Principal-Sample-Life-Insurance-Policy.pdf
1,Page 2,This page left blank intentionally,Principal-Sample-Life-Insurance-Policy.pdf
2,Page 3,POLICY RIDER GROUP INSURANCE POLICY NO: S655 C...,Principal-Sample-Life-Insurance-Policy.pdf
3,Page 4,This page left blank intentionally,Principal-Sample-Life-Insurance-Policy.pdf
4,Page 5,PRINCIPAL LIFE INSURANCE COMPANY (called The P...,Principal-Sample-Life-Insurance-Policy.pdf

In [ ]:
insurance_pdf_data['Metadata'] = insurance_pdf_data.apply(
    lambda x: {
        'filing_name': x['Document Name'][:-4],  # Removes ".pdf" from filename
        'Page_No.': x['Page No.']
    },
    axis=1
)

In [ ]:
insurance_pdf_data.head()

,Page No.,Page_Text,Document Name,Metadata
0,Page 1,DOROTHEA GLAUSE S655 RHODE ISLAND JOHN DOE 01/...,Principal-Sample-Life-Insurance-Policy.pdf,{'filing_name': 'Principal-Sample-Life-Insuran...
1,Page 2,This page left blank intentionally,Principal-Sample-Life-Insurance-Policy.pdf,{'filing_name': 'Principal-Sample-Life-Insuran...
2,Page 3,POLICY RIDER GROUP INSURANCE POLICY NO: S655 C...,Principal-Sample-Life-Insurance-Policy.pdf,{'filing_name': 'Principal-Sample-Life-Insuran...
3,Page 4,This page left blank intentionally,Principal-Sample-Life-Insurance-Policy.pdf,{'filing_name': 'Principal-Sample-Life-Insuran...
4,Page 5,PRINCIPAL LIFE INSURANCE COMPANY (called The P...,Principal-Sample-Life-Insurance-Policy.pdf,{'filing_name': 'Principal-Sample-Life-Insuran...

In [ ]:
all_chunks = []

for index, row in extracted_text_df.iterrows():
    page_chunks = chunk_text(row["Page_Text"], chunk_size=500, overlap=50, strategy="sliding")
    for i, chunk in enumerate(page_chunks):
        all_chunks.append({
            "Page_No.": row["Page No."],
            "Chunk_No.": f"{row['Page No.']}_Chunk_{i+1}",
            "Chunk_text": chunk,
            "Document_Name": row["Document Name"]
        })

chunked_df = pd.DataFrame(all_chunks)
print(chunked_df.head())

  Page_No.       Chunk_No.                                         Chunk_text  \
0   Page 1  Page 1_Chunk_1  DOROTHEA GLAUSE S655 RHODE ISLAND JOHN DOE 01/...
1   Page 2  Page 2_Chunk_1                 This page left blank intentionally
2   Page 3  Page 3_Chunk_1  POLICY RIDER GROUP INSURANCE POLICY NO: S655 C...
3   Page 4  Page 4_Chunk_1                 This page left blank intentionally
4   Page 5  Page 5_Chunk_1  PRINCIPAL LIFE INSURANCE COMPANY (called The P...

                                Document_Name
0  Principal-Sample-Life-Insurance-Policy.pdf
1  Principal-Sample-Life-Insurance-Policy.pdf
2  Principal-Sample-Life-Insurance-Policy.pdf
3  Principal-Sample-Life-Insurance-Policy.pdf
4  Principal-Sample-Life-Insurance-Policy.pdf

In [ ]:
chunked_df.head()

,Page_No.,Chunk_No.,Chunk_text,Document_Name
0,Page 1,Page 1_Chunk_1,DOROTHEA GLAUSE S655 RHODE ISLAND JOHN DOE 01/...,Principal-Sample-Life-Insurance-Policy.pdf
1,Page 2,Page 2_Chunk_1,This page left blank intentionally,Principal-Sample-Life-Insurance-Policy.pdf
2,Page 3,Page 3_Chunk_1,POLICY RIDER GROUP INSURANCE POLICY NO: S655 C...,Principal-Sample-Life-Insurance-Policy.pdf
3,Page 4,Page 4_Chunk_1,This page left blank intentionally,Principal-Sample-Life-Insurance-Policy.pdf
4,Page 5,Page 5_Chunk_1,PRINCIPAL LIFE INSURANCE COMPANY (called The P...,Principal-Sample-Life-Insurance-Policy.pdf

In [ ]:
chunked_df['Metadata'] = chunked_df.apply(
    lambda x: {
        'filing_name': x['Document_Name'][:-4],  # Removes ".pdf" from filename
        'Page_No.': x['Page_No.']
    },
    axis=1
)

In [ ]:
chunked_df.head()

,Page_No.,Chunk_No.,Chunk_text,Document_Name,Metadata
0,Page 1,Page 1_Chunk_1,DOROTHEA GLAUSE S655 RHODE ISLAND JOHN DOE 01/...,Principal-Sample-Life-Insurance-Policy.pdf,{'filing_name': 'Principal-Sample-Life-Insuran...
1,Page 2,Page 2_Chunk_1,This page left blank intentionally,Principal-Sample-Life-Insurance-Policy.pdf,{'filing_name': 'Principal-Sample-Life-Insuran...
2,Page 3,Page 3_Chunk_1,POLICY RIDER GROUP INSURANCE POLICY NO: S655 C...,Principal-Sample-Life-Insurance-Policy.pdf,{'filing_name': 'Principal-Sample-Life-Insuran...
3,Page 4,Page 4_Chunk_1,This page left blank intentionally,Principal-Sample-Life-Insurance-Policy.pdf,{'filing_name': 'Principal-Sample-Life-Insuran...
4,Page 5,Page 5_Chunk_1,PRINCIPAL LIFE INSURANCE COMPANY (called The P...,Principal-Sample-Life-Insurance-Policy.pdf,{'filing_name': 'Principal-Sample-Life-Insuran...

In [ ]:
print(len(insurance_pdf_data))
print(len(chunked_df))

64
66

### Chroma Database

In [ ]:
!pip install chromadb

Collecting chromadb
  Downloading chromadb-1.0.13-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.0 kB)
Requirement already satisfied: build>=1.0.3 in /usr/local/lib/python3.11/dist-packages (from chromadb) (1.2.2.post1)
Requirement already satisfied: pydantic>=1.9 in /usr/local/lib/python3.11/dist-packages (from chromadb) (2.11.7)
Collecting pybase64>=1.4.1 (from chromadb)
  Downloading pybase64-1.4.1-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: uvicorn>=0.18.3 in /usr/local/lib/python3.11/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.34.3)
Requirement already satisfied: numpy>=1.22.5 in /usr/local/lib/python3.11/dist-packages (from chromadb) (2.0.2)
Collecting posthog>=2.4.0 (from chromadb)
  Downloading posthog-6.0.1-py3-none-any.whl.metadata (6.0 kB)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.11/dist-packages (from chromadb) (4.14.0)
Collecting onnxruntime>=1.14.1 (from chromadb)
  Downloading onnxruntime-1.22.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (4.5 kB)
Collecting opentelemetry-api>=1.2.0 (from chromadb)
  Downloading opentelemetry_api-1.34.1-py3-none-any.whl.metadata (1.5 kB)
Collecting opentelemetry-exporter-otlp-proto-grpc>=1.2.0 (from chromadb)
  Downloading opentelemetry_exporter_otlp_proto_grpc-1.34.1-py3-none-any.whl.metadata (2.4 kB)
Collecting opentelemetry-sdk>=1.2.0 (from chromadb)
  Downloading opentelemetry_sdk-1.34.1-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: tokenizers>=0.13.2 in /usr/local/lib/python3.11/dist-packages (from chromadb) (0.21.2)
Collecting pypika>=0.48.9 (from chromadb)
  Downloading PyPika-0.48.9.tar.gz (67 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.3/67.3 kB 1.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: tqdm>=4.65.0 in /usr/local/lib/python3.11/dist-packages (from chromadb) (4.67.1)
Collecting overrides>=7.3.1 (from chromadb)
  Downloading overrides-7.7.0-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.11/dist-packages (from chromadb) (6.5.2)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.11/dist-packages (from chromadb) (1.73.0)
Collecting bcrypt>=4.0.1 (from chromadb)
  Downloading bcrypt-4.3.0-cp39-abi3-manylinux_2_34_x86_64.whl.metadata (10 kB)
Requirement already satisfied: typer>=0.9.0 in /usr/local/lib/python3.11/dist-packages (from chromadb) (0.16.0)
Collecting kubernetes>=28.1.0 (from chromadb)
  Downloading kubernetes-33.1.0-py2.py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: tenacity>=8.2.3 in /usr/local/lib/python3.11/dist-packages (from chromadb) (8.5.0)
Requirement already satisfied: pyyaml>=6.0.0 in /usr/local/lib/python3.11/dist-packages (from chromadb) (6.0.2)
Collecting mmh3>=4.0.1 (from chromadb)
  Downloading mmh3-5.1.0-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (16 kB)
Requirement already satisfied: orjson>=3.9.12 in /usr/local/lib/python3.11/dist-packages (from chromadb) (3.10.18)
Requirement already satisfied: httpx>=0.27.0 in /usr/local/lib/python3.11/dist-packages (from chromadb) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.11/dist-packages (from chromadb) (13.9.4)
Requirement already satisfied: jsonschema>=4.19.0 in /usr/local/lib/python3.11/dist-packages (from chromadb) (4.24.0)
Requirement already satisfied: packaging>=19.1 in /usr/local/lib/python3.11/dist-packages (from build>=1.0.3->chromadb) (24.2)
Requirement already satisfied: pyproject_hooks in /usr/local/lib/python3.11/dist-packages (from build>=1.0.3->chromadb) (1.2.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.11/dist-packages (from httpx>=0.27.0->chromadb) (4.9.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx>=0.27.0->chromadb) (2025.6.15)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx>=0.27.0->chromadb) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages (from httpx>=0.27.0->chromadb) (3.10)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx>=0.27.0->chromadb) (0.16.0)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=4.19.0->chromadb) (25.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=4.19.0->chromadb) (2025.4.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=4.19.0->chromadb) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.11/dist-packages (from jsonschema>=4.19.0->chromadb) (0.25.1)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.11/dist-packages (from kubernetes>=28.1.0->chromadb) (1.17.0)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.11/dist-packages (from kubernetes>=28.1.0->chromadb) (2.9.0.post0)
Requirement already satisfied: google-auth>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from kubernetes>=28.1.0->chromadb) (2.38.0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.11/dist-packages (from kubernetes>=28.1.0->chromadb) (1.8.0)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from kubernetes>=28.1.0->chromadb) (2.32.3)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.11/dist-packages (from kubernetes>=28.1.0->chromadb) (2.0.0)
Requirement already satisfied: oauthlib>=3.2.2 in /usr/local/lib/python3.11/dist-packages (from kubernetes>=28.1.0->chromadb) (3.3.1)
Requirement already satisfied: urllib3>=1.24.2 in /usr/local/lib/python3.11/dist-packages (from kubernetes>=28.1.0->chromadb) (2.4.0)
Collecting durationpy>=0.7 (from kubernetes>=28.1.0->chromadb)
  Downloading durationpy-0.10-py3-none-any.whl.metadata (340 bytes)
Collecting coloredlogs (from onnxruntime>=1.14.1->chromadb)
  Downloading coloredlogs-15.0.1-py2.py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.11/dist-packages (from onnxruntime>=1.14.1->chromadb) (25.2.10)
Requirement already satisfied: protobuf in /usr/local/lib/python3.11/dist-packages (from onnxruntime>=1.14.1->chromadb) (5.29.5)
Requirement already satisfied: sympy in /usr/local/lib/python3.11/dist-packages (from onnxruntime>=1.14.1->chromadb) (1.13.1)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in /usr/local/lib/python3.11/dist-packages (from opentelemetry-api>=1.2.0->chromadb) (8.7.0)
Requirement already satisfied: googleapis-common-protos~=1.52 in /usr/local/lib/python3.11/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.70.0)
Collecting opentelemetry-exporter-otlp-proto-common==1.34.1 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Downloading opentelemetry_exporter_otlp_proto_common-1.34.1-py3-none-any.whl.metadata (1.9 kB)
Collecting opentelemetry-proto==1.34.1 (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb)
  Downloading opentelemetry_proto-1.34.1-py3-none-any.whl.metadata (2.4 kB)
Collecting opentelemetry-semantic-conventions==0.55b1 (from opentelemetry-sdk>=1.2.0->chromadb)
  Downloading opentelemetry_semantic_conventions-0.55b1-py3-none-any.whl.metadata (2.5 kB)
Collecting backoff>=1.10.0 (from posthog>=2.4.0->chromadb)
  Downloading backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: distro>=1.5.0 in /usr/local/lib/python3.11/dist-packages (from posthog>=2.4.0->chromadb) (1.9.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=1.9->chromadb) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.11/dist-packages (from pydantic>=1.9->chromadb) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=1.9->chromadb) (0.4.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->chromadb) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.11/dist-packages (from rich>=10.11.0->chromadb) (2.19.2)
Requirement already satisfied: huggingface-hub<1.0,>=0.16.4 in /usr/local/lib/python3.11/dist-packages (from tokenizers>=0.13.2->chromadb) (0.33.0)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from typer>=0.9.0->chromadb) (8.2.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from typer>=0.9.0->chromadb) (1.5.4)
Collecting httptools>=0.6.3 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading httptools-0.6.4-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.6 kB)
Collecting python-dotenv>=0.13 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading python_dotenv-1.1.1-py3-none-any.whl.metadata (24 kB)
Collecting uvloop>=0.15.1 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading uvloop-0.21.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Collecting watchfiles>=0.13 (from uvicorn[standard]>=0.18.3->chromadb)
  Downloading watchfiles-1.1.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: websockets>=10.4 in /usr/local/lib/python3.11/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (15.0.1)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.11/dist-packages (from google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (4.9.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (2025.3.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (1.1.5)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.11/dist-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api>=1.2.0->chromadb) (3.23.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb) (0.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->kubernetes>=28.1.0->chromadb) (3.4.2)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio->httpx>=0.27.0->chromadb) (1.3.1)
Collecting humanfriendly>=9.1 (from coloredlogs->onnxruntime>=1.14.1->chromadb)
  Downloading humanfriendly-10.0-py2.py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy->onnxruntime>=1.14.1->chromadb) (1.3.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.11/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=1.0.1->kubernetes>=28.1.0->chromadb) (0.6.1)
Downloading chromadb-1.0.13-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (19.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.3/19.3 MB 81.3 MB/s eta 0:00:00
Downloading bcrypt-4.3.0-cp39-abi3-manylinux_2_34_x86_64.whl (284 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 284.2/284.2 kB 19.1 MB/s eta 0:00:00
Downloading kubernetes-33.1.0-py2.py3-none-any.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 78.2 MB/s eta 0:00:00
Downloading mmh3-5.1.0-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (101 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.6/101.6 kB 7.6 MB/s eta 0:00:00
Downloading onnxruntime-1.22.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 97.2 MB/s eta 0:00:00
Downloading opentelemetry_api-1.34.1-py3-none-any.whl (65 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.8/65.8 kB 569.0 kB/s eta 0:00:00
Downloading opentelemetry_exporter_otlp_proto_grpc-1.34.1-py3-none-any.whl (18 kB)
Downloading opentelemetry_exporter_otlp_proto_common-1.34.1-py3-none-any.whl (18 kB)
Downloading opentelemetry_proto-1.34.1-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.7/55.7 kB 4.2 MB/s eta 0:00:00
Downloading opentelemetry_sdk-1.34.1-py3-none-any.whl (118 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.5/118.5 kB 8.6 MB/s eta 0:00:00
Downloading opentelemetry_semantic_conventions-0.55b1-py3-none-any.whl (196 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.2/196.2 kB 13.9 MB/s eta 0:00:00
Downloading overrides-7.7.0-py3-none-any.whl (17 kB)
Downloading posthog-6.0.1-py3-none-any.whl (104 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.0/105.0 kB 8.3 MB/s eta 0:00:00
Downloading pybase64-1.4.1-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.2/71.2 kB 5.6 MB/s eta 0:00:00
Downloading backoff-2.2.1-py3-none-any.whl (15 kB)
Downloading durationpy-0.10-py3-none-any.whl (3.9 kB)
Downloading httptools-0.6.4-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (459 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 459.8/459.8 kB 31.6 MB/s eta 0:00:00
Downloading python_dotenv-1.1.1-py3-none-any.whl (20 kB)
Downloading uvloop-0.21.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 97.6 MB/s eta 0:00:00
Downloading watchfiles-1.1.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (453 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 453.1/453.1 kB 27.9 MB/s eta 0:00:00
Downloading coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.0/46.0 kB 3.3 MB/s eta 0:00:00
Downloading humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.8/86.8 kB 7.0 MB/s eta 0:00:00
Building wheels for collected packages: pypika
  Building wheel for pypika (pyproject.toml) ... done
  Created wheel for pypika: filename=pypika-0.48.9-py2.py3-none-any.whl size=53803 sha256=5247054cc01e6c8b718ab5a186e7d4e15d980396f1a4eb949e2f0a7544aa3030
  Stored in directory: /root/.cache/pip/wheels/a3/01/bd/4c40ceb9d5354160cb186dcc153360f4ab7eb23e2b24daf96d
Successfully built pypika
Installing collected packages: pypika, durationpy, uvloop, python-dotenv, pybase64, overrides, opentelemetry-proto, mmh3, humanfriendly, httptools, bcrypt, backoff, watchfiles, posthog, opentelemetry-exporter-otlp-proto-common, opentelemetry-api, coloredlogs, opentelemetry-semantic-conventions, onnxruntime, kubernetes, opentelemetry-sdk, opentelemetry-exporter-otlp-proto-grpc, chromadb
Successfully installed backoff-2.2.1 bcrypt-4.3.0 chromadb-1.0.13 coloredlogs-15.0.1 durationpy-0.10 httptools-0.6.4 humanfriendly-10.0 kubernetes-33.1.0 mmh3-5.1.0 onnxruntime-1.22.0 opentelemetry-api-1.34.1 opentelemetry-exporter-otlp-proto-common-1.34.1 opentelemetry-exporter-otlp-proto-grpc-1.34.1 opentelemetry-proto-1.34.1 opentelemetry-sdk-1.34.1 opentelemetry-semantic-conventions-0.55b1 overrides-7.7.0 posthog-6.0.1 pybase64-1.4.1 pypika-0.48.9 python-dotenv-1.1.1 uvloop-0.21.0 watchfiles-1.1.0

In [ ]:
# Importing the OpenAI Embedding Function into Chroma
import chromadb
from chromadb.config import Settings
from chromadb.utils.embedding_functions import OpenAIEmbeddingFunction

In [ ]:
chromadb_data_path = '/content/drive/MyDrive/GenAI_Course_Master/HelpMate_AI/ChromaDB_presistpath_Chuncking'

In [ ]:
import logging
logging.getLogger("chromadb.telemetry").setLevel(logging.CRITICAL)

In [ ]:
chroma_client = chromadb.PersistentClient(path=chromadb_data_path,settings=Settings(anonymized_telemetry=False))

In [ ]:
model = 'text-embedding-ada-002'
embedding_functions = OpenAIEmbeddingFunction(api_key=api_key, model_name=model)

In [ ]:
insurance_collection = chroma_client.get_or_create_collection(name='Insurance_RAG', embedding_function=embedding_functions)

In [ ]:
insurance_collection

Collection(name=Insurance_RAG)

In [ ]:
documents_list = chunked_df['Chunk_text'].tolist()
metadata_list = chunked_df['Metadata'].tolist()

In [ ]:
insurance_collection.add(
    documents = documents_list,
    ids = [str(i) for i in range(0, len(documents_list))],
    metadatas = metadata_list
)

In [ ]:
insurance_collection

Collection(name=Insurance_RAG)

In [ ]:
insurance_collection.peek(2)

{'ids': ['0', '1'],
 'embeddings': array([[-0.02251517,  0.01869307, -0.02726344, ..., -0.03691652,
          0.00289266, -0.00121071],
        [-0.01595563,  0.00016479,  0.0027096 , ..., -0.01704412,
          0.0027544 , -0.02559273]]),
 'documents': ['DOROTHEA GLAUSE S655 RHODE ISLAND JOHN DOE 01/01/2014 711 HIGH STREET GEORGE RI 02903 GROUP POLICY FOR: RHODE ISLAND JOHN DOE ALL MEMBERS Group Member Life Insurance Print Date: 07/16/2014',
  'This page left blank intentionally'],
 'uris': None,
 'included': ['metadatas', 'documents', 'embeddings'],
 'data': None,
 'metadatas': [{'Page_No.': 'Page 1',
   'filing_name': 'Principal-Sample-Life-Insurance-Policy'},
  {'filing_name': 'Principal-Sample-Life-Insurance-Policy',
   'Page_No.': 'Page 2'}]}

In [ ]:
cache_collection = chroma_client.get_or_create_collection(name='cache_Insurance_RAG', embedding_function=embedding_functions)

In [ ]:
cache_collection.peek(2)

{'ids': [],
 'embeddings': array([], dtype=float64),
 'documents': [],
 'uris': None,
 'included': ['metadatas', 'documents', 'embeddings'],
 'data': None,
 'metadatas': []}

### Reading User Query

In [ ]:
query = input()

Death benifits

In [ ]:
query

'Death benifits'

In [ ]:
results = insurance_collection.query(
    query_texts=query,
    n_results=2
)

In [ ]:
results

{'ids': [['48', '7']],
 'embeddings': None,
 'documents': [["M ember's death, the Death Benefits Payable may be withheld until additional information has been received or the trial has been held. If a Member who was insured dies within the 31-day individual purchase period described in PART III, Section F, The Principal will pay his or her beneficiary the individual policy amount, if any, the Member had the right to purchase. No payment will be made before The Principal receives Written proof of the Member's death. Article 3 - Beneficiary A beneficiary should be named at the time a Member applies or enrolls under this Group Policy. A Member may name or later change a named beneficiary by sending a Written request to The Principal. A change will not be effective until recorded by The Principal. Once recorded, the change will apply as of the date the request was Signed. If The Principal properly pays any benefit before a change request is received, that payment may not be contested. Further: a. The naming of a new beneficiary in an application for individual purchase under PART III, Section F, Article 1, will be treated as a beneficiary change request under this Group Policy. b. If a Member's terminated insurance is reinstated, his or her beneficiary will be as recorded on the date of termination. If a Member is insured under this Group Policy on its Date of Issue and this insurance replaces insurance in force on the day immediately before the Date of Issue, the beneficiary named in such replaced insurance and recorded by the Policyholder or The Principal will be the beneficiary under this Group Policy until a new beneficiary is named. Article 4 - Facility of Payment If any of the below occur, benefits will be paid as stated. All such payments will discharge The Principal to the full extent of those payments. a. If a beneficiary is found guilty of the Member's death, such beneficiary may be disqualified from receiving any benefit due. Payment may then be made to any contingent beneficiary or to the executor or administrator of the Member's estate. b. Any benefit due a beneficiary who dies before the Member's death will be paid in equal shares to the Member's surviving beneficiaries. This policy has been updated effective January 1, 2014 PART IV - BENEFITS GC 6013 Section A - Member Life Insurance, Page 2",
   'Section A - Member Life Insurance Schedule of Insurance Article 1 Death Benefits Payable Article 2 Beneficiary Article 3 Facility of Payment Article 4 Settlement of Proceeds Article 5 Member Life Insurance - Coverage During Disability Article 6 Accelerated Benefits Article 7 Section B - Member Accidental Death and Dismemberment Insurance Schedule of Insurance Article 1 Benefit Qualification Article 2 Benefits Payable Article 3 Seat Belt Benefit Article 4 Loss of Use or Paralysis Benefit Article 5 Loss of Speech and/or Hearing Benefit Article 6 Repatriation Benefit Article 7 Educational Benefit Article 8 Limitations Article 9 Section C - Dependent Life Insurance Schedule of Insurance Article 1 Death Benefits Payable Article 2 Beneficiary Article 3 Section D - Claim Procedures Notice of Claim Article 1 Claim Forms Article 2 Proof of Loss Article 3 Payment, Denial and Review Article 4 Medical Examinations Article 5 Autopsy Article 6 Legal Action Article 7 Time Limits Article 8 This policy has been updated effective January 1, 2014 GC 6001 TABLE OF CONTENTS, PAGE 3']],
 'uris': None,
 'included': ['metadatas', 'documents', 'distances'],
 'data': None,
 'metadatas': [[{'filing_name': 'Principal-Sample-Life-Insurance-Policy',
    'Page_No.': 'Page 47'},
   {'filing_name': 'Principal-Sample-Life-Insurance-Policy',
    'Page_No.': 'Page 8'}]],
 'distances': [[0.28931906819343567, 0.31424590945243835]]}

In [ ]:
for key, value in results.items():
  print(key)

ids
embeddings
documents
uris
included
data
metadatas
distances

In [ ]:
for key, value in results.items():
  print(key)
  print(value)

ids
[['48', '7']]
embeddings
None
documents
[["M ember's death, the Death Benefits Payable may be withheld until additional information has been received or the trial has been held. If a Member who was insured dies within the 31-day individual purchase period described in PART III, Section F, The Principal will pay his or her beneficiary the individual policy amount, if any, the Member had the right to purchase. No payment will be made before The Principal receives Written proof of the Member's death. Article 3 - Beneficiary A beneficiary should be named at the time a Member applies or enrolls under this Group Policy. A Member may name or later change a named beneficiary by sending a Written request to The Principal. A change will not be effective until recorded by The Principal. Once recorded, the change will apply as of the date the request was Signed. If The Principal properly pays any benefit before a change request is received, that payment may not be contested. Further: a. The naming of a new beneficiary in an application for individual purchase under PART III, Section F, Article 1, will be treated as a beneficiary change request under this Group Policy. b. If a Member's terminated insurance is reinstated, his or her beneficiary will be as recorded on the date of termination. If a Member is insured under this Group Policy on its Date of Issue and this insurance replaces insurance in force on the day immediately before the Date of Issue, the beneficiary named in such replaced insurance and recorded by the Policyholder or The Principal will be the beneficiary under this Group Policy until a new beneficiary is named. Article 4 - Facility of Payment If any of the below occur, benefits will be paid as stated. All such payments will discharge The Principal to the full extent of those payments. a. If a beneficiary is found guilty of the Member's death, such beneficiary may be disqualified from receiving any benefit due. Payment may then be made to any contingent beneficiary or to the executor or administrator of the Member's estate. b. Any benefit due a beneficiary who dies before the Member's death will be paid in equal shares to the Member's surviving beneficiaries. This policy has been updated effective January 1, 2014 PART IV - BENEFITS GC 6013 Section A - Member Life Insurance, Page 2", 'Section A - Member Life Insurance Schedule of Insurance Article 1 Death Benefits Payable Article 2 Beneficiary Article 3 Facility of Payment Article 4 Settlement of Proceeds Article 5 Member Life Insurance - Coverage During Disability Article 6 Accelerated Benefits Article 7 Section B - Member Accidental Death and Dismemberment Insurance Schedule of Insurance Article 1 Benefit Qualification Article 2 Benefits Payable Article 3 Seat Belt Benefit Article 4 Loss of Use or Paralysis Benefit Article 5 Loss of Speech and/or Hearing Benefit Article 6 Repatriation Benefit Article 7 Educational Benefit Article 8 Limitations Article 9 Section C - Dependent Life Insurance Schedule of Insurance Article 1 Death Benefits Payable Article 2 Beneficiary Article 3 Section D - Claim Procedures Notice of Claim Article 1 Claim Forms Article 2 Proof of Loss Article 3 Payment, Denial and Review Article 4 Medical Examinations Article 5 Autopsy Article 6 Legal Action Article 7 Time Limits Article 8 This policy has been updated effective January 1, 2014 GC 6001 TABLE OF CONTENTS, PAGE 3']]
uris
None
included
['metadatas', 'documents', 'distances']
data
None
metadatas
[[{'filing_name': 'Principal-Sample-Life-Insurance-Policy', 'Page_No.': 'Page 47'}, {'filing_name': 'Principal-Sample-Life-Insurance-Policy', 'Page_No.': 'Page 8'}]]
distances
[[0.28931906819343567, 0.31424590945243835]]

In [ ]:
for key, val in results.items():
  if key not in ['embedding', 'uris', 'data']:
    for i in range (10):
      print(str(key)+str(i))

ids0
ids1
ids2
ids3
ids4
ids5
ids6
ids7
ids8
ids9
embeddings0
embeddings1
embeddings2
embeddings3
embeddings4
embeddings5
embeddings6
embeddings7
embeddings8
embeddings9
documents0
documents1
documents2
documents3
documents4
documents5
documents6
documents7
documents8
documents9
included0
included1
included2
included3
included4
included5
included6
included7
included8
included9
metadatas0
metadatas1
metadatas2
metadatas3
metadatas4
metadatas5
metadatas6
metadatas7
metadatas8
metadatas9
distances0
distances1
distances2
distances3
distances4
distances5
distances6
distances7
distances8
distances9

In [ ]:
# Query the cache collection againts the user query and return the top results
cache_results = cache_collection.query(
    query_texts=query,
    n_results=1
)

In [ ]:
cache_results

{'ids': [[]],
 'embeddings': None,
 'documents': [[]],
 'uris': None,
 'included': ['metadatas', 'documents', 'distances'],
 'data': None,
 'metadatas': [[]],
 'distances': [[]]}

In [ ]:
cache_results['distances'][0]

[]

### Implementing Cache in Semantic Search

In [ ]:
from functools import cache
threshold = 0.2 # Setting a threshold for cache search

ids = []
documents = []
distances = []
metadatas = []
results_df = pd.DataFrame()

# If the distance is greater than the threshold, then return the results from the main collection.

if cache_results['distances'][0] == [] or cache_results['distances'][0][0] > threshold:
  # Query the collection against the user query and return the top 10 results
  results = insurance_collection.query(
      query_texts=query,
      n_results=10
  )

  # Storing the query in cache_collection as document w.r.t to ChromaDB so that it can be embedded and searched against later
  # Storing retrieved text, ids, distances and metadatas in cache_collection as metadatas, so that they can be fetched easily if a query indeed matches to a query in cache

  keys = []
  values = []

  for key, value in results.items():
    if key not in ['embedding', 'uris', 'data'] and value is not None:
        for i, item in enumerate(value[0]):
            keys.append(f"{key}{i}")
            values.append(str(item))

  cache_collection.add(
      documents = [query],
      ids=[query],
      metadatas=dict(zip(keys, values))
  )

  print("Result not found in cache. Returning results from main collection.")

  result_dict = {'ids': results['ids'][0], 'documents': results['documents'][0], 'distances': results['distances'][0], 'metadatas': results['metadatas'][0]}
  results_df = pd.DataFrame(result_dict)
  results_df

# If the distance is, however, less than the threshold, you can return the results from cache

elif cache_results['distances'][0][0] < threshold:
  cache_results_dict = cache_results['metadatas'][0][0]

  # Loop through each inner list and then through the dictionary
  for key, value in cache_results_dict.items():
    if 'documents' in key:
      documents.append(value)
    elif 'ids' in key:
      ids.append(value)
    elif 'distances' in key:
      distances.append(value)
    elif 'metadatas' in key:
      metadatas.append(value)
  print("Result found in cache. Returning results from cache.")

  # Creating a Dataframe
  results_df = pd.DataFrame({
        'IDs': ids,
        'Documents': documents,
        'Distances': distances,
        'Metadatas': metadatas
      })

Result not found in cache. Returning results from main collection.

In [ ]:
results_df

,ids,documents,distances,metadatas
0,48,"M ember's death, the Death Benefits Payable ma...",0.289319,"{'Page_No.': 'Page 47', 'filing_name': 'Princi..."
1,7,Section A - Member Life Insurance Schedule of ...,0.314246,"{'Page_No.': 'Page 8', 'filing_name': 'Princip..."
2,61,I f a Dependent who was insured dies during th...,0.320214,"{'Page_No.': 'Page 60', 'filing_name': 'Princi..."
3,55,"f . claim requirements listed in PART IV, Sect...",0.320991,"{'Page_No.': 'Page 54', 'filing_name': 'Princi..."
4,58,% of Scheduled Covered Loss Benefit Loss of Sp...,0.322053,"{'Page_No.': 'Page 57', 'filing_name': 'Princi..."
5,32,(1) marriage or establishment of a Civil Union...,0.326675,"{'Page_No.': 'Page 32', 'filing_name': 'Princi..."
6,56,Exposure Exposure to the elements will be pres...,0.343172,{'filing_name': 'Principal-Sample-Life-Insuran...
7,52,Coverage During Disability will cease on the e...,0.345069,{'filing_name': 'Principal-Sample-Life-Insuran...
8,46,(1) If termination is as described in b. (1) a...,0.350154,{'filing_name': 'Principal-Sample-Life-Insuran...
9,60,Section C - Dependent Life Insurance Article 1...,0.351510,"{'Page_No.': 'Page 59', 'filing_name': 'Princi..."

In [ ]:
cache_results = cache_collection.query(
    query_texts=query,
    n_results=1
)
cache_results

{'ids': [['Death benifits']],
 'embeddings': None,
 'documents': [['Death benifits']],
 'uris': None,
 'included': ['metadatas', 'documents', 'distances'],
 'data': None,
 'metadatas': [[{'distances5': '0.3266754150390625',
    'included1': 'e',
    'documents4': '% of Scheduled Covered Loss Benefit Loss of Speech and/or Hearing Speech and Hearing 100% Speech or Hearing 50% Hearing in One Ear 25% Loss must be determined by a Physician to be permanent, complete, and irreversible. Total payment for all losses that result from the same accident will not exceed the Scheduled Benefit (or approved amount, if applicable). Payment for Loss will be to the Member. For this benefit, the term "Loss" means a total and irrevocable Loss of speech or hearing, which has continued for 12 consecutive months. Article 7 - Repatriation Benefit If a benefit is paid under this Section B for loss of the Member\'s life and death occurred at least 100 miles away from the Member\'s permanent place of residence, all customary and reasonable expenses incurred for preparation of the body and its transportation to the place of burial or cremation will be paid up to a maximum benefit payment of $2,000. Article 8 - Educational Benefit If a benefit is paid under this Section B for loss of the Member\'s life, an extra benefit of $3,000 will be paid annually for a maximum of four years to each Qualified Student. This annual benefit will be paid consecutively, while the Qualified Student continues his or her education as a Full-Time Student at an accredited post-secondary school. For the purpose of this benefit, "Qualified Student" means a Dependent Child who is, at the time of the Member\'s death, a Full-Time Student at an accredited post-secondary school. A 12th grade student will become a Qualified Student if he or she enrolls in an accredited post- secondary school within 12 months of the Member\'s death. Article 9 - Limitations Payment will not be made for any loss to which a contributing cause is: This policy has been updated effective January 1, 2014 PART IV - BENEFITS GC 6015 Section B - Member Accidental Death and Dismemberment Insurance, Page 5',
    'documents0': "M ember's death, the Death Benefits Payable may be withheld until additional information has been received or the trial has been held. If a Member who was insured dies within the 31-day individual purchase period described in PART III, Section F, The Principal will pay his or her beneficiary the individual policy amount, if any, the Member had the right to purchase. No payment will be made before The Principal receives Written proof of the Member's death. Article 3 - Beneficiary A beneficiary should be named at the time a Member applies or enrolls under this Group Policy. A Member may name or later change a named beneficiary by sending a Written request to The Principal. A change will not be effective until recorded by The Principal. Once recorded, the change will apply as of the date the request was Signed. If The Principal properly pays any benefit before a change request is received, that payment may not be contested. Further: a. The naming of a new beneficiary in an application for individual purchase under PART III, Section F, Article 1, will be treated as a beneficiary change request under this Group Policy. b. If a Member's terminated insurance is reinstated, his or her beneficiary will be as recorded on the date of termination. If a Member is insured under this Group Policy on its Date of Issue and this insurance replaces insurance in force on the day immediately before the Date of Issue, the beneficiary named in such replaced insurance and recorded by the Policyholder or The Principal will be the beneficiary under this Group Policy until a new beneficiary is named. Article 4 - Facility of Payment If any of the below occur, benefits will be paid as stated. All such payments will discharge The Principal to the full extent of those payments. a. If a beneficiary is found guilty of the Member's death, such beneficiary may be disqualified from receiving any benefit due. Payment may then be made to any contingent beneficiary or to the executor or administrator of the Member's estate. b. Any benefit due a beneficiary who dies before the Member's death will be paid in equal shares to the Member's surviving beneficiaries. This policy has been updated effective January 1, 2014 PART IV - BENEFITS GC 6013 Section A - Member Life Insurance, Page 2",
    'metadatas8': "{'filing_name': 'Principal-Sample-Life-Insurance-Policy', 'Page_No.': 'Page 45'}",
    'metadatas7': "{'filing_name': 'Principal-Sample-Life-Insurance-Policy', 'Page_No.': 'Page 51'}",
    'metadatas9': "{'Page_No.': 'Page 59', 'filing_name': 'Principal-Sample-Life-Insurance-Policy'}",
    'distances9': '0.351510226726532',
    'documents6': 'Exposure Exposure to the elements will be presumed to be an injury if: a. such exposure is due to an accidental bodily injury; and b. within 365 days after the injury, the Member incurs a loss that is the result of the exposure; and c. this Group Policy would have covered the injury resulting from the accident. Article 4 - Seat Belt/Airbag Benefit If the Member loses his or her life as a result of an accidental injury sustained while driving or riding in an Automobile, an additional benefit of $10,000 will be paid to the beneficiary named for Member Life Insurance, provided all Benefit Qualifications as described in Article 2 are met and: a. the Automobile is equipped with factory-installed Seat Belts; and b. the Seat Belt was in actual use by the Member and properly fastened at the time of the accident; and c. the position of the Seat Belt is certified in the official report of the accident or by the investigating officer. This additional benefit payment will also apply if the Member was driving an Automobile equipped with a properly functioning driver-side air bag or riding as a passenger in an Automobile equipped with a properly functioning passenger-side air bag, although the Member\'s Seat Belt may not have been fastened at the time of the accident. The properly functioning and/or deployment of the air bag must be certified in the official report of the accident or by the investigating officer. For the purpose of this benefit, "Automobile" means a four-wheel passenger vehicle, station wagon, pick-up truck, or van-type vehicle, but excludes recreational-type vehicles such as a "dune-buggy" or an "all-terrain" vehicle. The term "Seat Belt" means a factory-installed device that forms an occupant restraint and injury avoidance system. Article 5 - Loss of Use or Paralysis Benefit This policy has been updated effective January 1, 2014 PART IV - BENEFITS GC 6015 Section B - Member Accidental Death and Dismemberment Insurance, Page 3',
    'documents1': 'Section A - Member Life Insurance Schedule of Insurance Article 1 Death Benefits Payable Article 2 Beneficiary Article 3 Facility of Payment Article 4 Settlement of Proceeds Article 5 Member Life Insurance - Coverage During Disability Article 6 Accelerated Benefits Article 7 Section B - Member Accidental Death and Dismemberment Insurance Schedule of Insurance Article 1 Benefit Qualification Article 2 Benefits Payable Article 3 Seat Belt Benefit Article 4 Loss of Use or Paralysis Benefit Article 5 Loss of Speech and/or Hearing Benefit Article 6 Repatriation Benefit Article 7 Educational Benefit Article 8 Limitations Article 9 Section C - Dependent Life Insurance Schedule of Insurance Article 1 Death Benefits Payable Article 2 Beneficiary Article 3 Section D - Claim Procedures Notice of Claim Article 1 Claim Forms Article 2 Proof of Loss Article 3 Payment, Denial and Review Article 4 Medical Examinations Article 5 Autopsy Article 6 Legal Action Article 7 Time Limits Article 8 This policy has been updated effective January 1, 2014 GC 6001 TABLE OF CONTENTS, PAGE 3',
    'ids0': '48',
    'included2': 't',
    'included6': 't',
    'documents2': "I f a Dependent who was insured dies during the 31-day individual purchase period described in PART III, Section F, Article 2, The Principal will pay the individual policy amount, if any, the Dependent had the right to purchase. Unless a Beneficiary has been designated, payment will be to the Member if he or she survives the Dependent. If the Member does not survive the Dependent and a beneficiary for Dependent Life has not been named, payment will be to the person named as beneficiary for Member Life Insurance. However, if the Member is suspected or charged with the Dependent's death, the Death Benefits Payable may be withheld until additional information has been received or the trial has been held. If the Member is found guilty of the Dependent's death, he or she may be disqualified from receiving any benefit due. Payment may then be made to the executor or administrator of the Dependent's estate. Payment will be subject to the Beneficiary provisions in Article 3 and the Facility of Payment and Settlement of Proceeds provisions of PART IV, Section A. No payment will be made before The Principal receives Written proof of the Dependent's death. Article 3 - Beneficiary A Member may name or later change a named beneficiary by sending a Written request to The Principal. A change will not be effective until recorded by The Principal. Once recorded, the change will apply as of the date the request was Signed. If The Principal properly pays any benefit before a change request is received, that payment may not be contested. This policy has been updated effective January 1, 2014 PART IV - BENEFITS GC 6016 Section C - Dependent Life Insurance, Page 2",
    'distances7': '0.3450692296028137',
    'ids9': '60',
    'distances8': '0.3501535952091217',
    'included8': 's',
    'documents8': '(1) If termination is as described in b. (1) above, the maximum amount will be the Dependent Life Insurance benefit in force for the Dependent on the date of termination or the portion of Dependent Life Insurance that has terminated, less any individual policy amount purchased earlier under this Article 2. (2) If termination is as described in b. (2), b. (3) or b. (5) or b. (6) above, the maximum amount will be the Dependent Life Insurance benefit in force for the Dependent on the date of termination, less any individual policy amount purchased earlier under this Article 2. (3) If termination is as described in b. (4) above, the maximum amount will be the lesser of: - $10,000; or - the Dependent Life Insurance benefit in force for the Dependent on the date of termination, less the amount for which the Dependent becomes eligible under any group policy within 31 days. This policy has been updated effective January 1, 2014 PART III - INDIVIDUAL REQUIREMENTS AND RIGHTS GC 6011 Section F - Individual Purchase Rights, Page 4',
    'documents5': "(1) marriage or establishment of a Civil Union partnership or divorce or termination of a Civil Union partnership; (2) death of a spouse or child; (3) birth or adoption of a child; (4) termination of employment by the Member's spouse or a change in the spouse's employment that causes loss of group coverage; (5) the Member's employment or the Member's spouse's employment changes from part- time to full-time or from full-time to part-time; (6) the Member or the Member's spouse takes an unpaid leave of absence. A change in the Scheduled Benefits because of a request by the Member when a change in family status has occurred for which Proof of Good Health is not required (see e. above) will normally be effective on the date of the request. However, if the Member is not Actively at Work on the date a Scheduled Benefit change would otherwise be effective, the Scheduled Benefit change will not be in force until the date the Member returns to Active Work. Any decrease in Scheduled Benefit amounts due to a request by the Member will be effective on the date of the change, whether or not the Member is Actively at Work. A change in the Scheduled Benefits because of a request by the Member when a change in family status has occurred for which Proof of Good Health is required (see e. above) will be effective on the later of: (1) the date the change would have been effective if Proof of Good Health had not been required; or (2) the date Proof of Good Health is approved by The Principal. Article 2 - Member Accidental Death and Dismemberment Insurance Member Accidental Death and Dismemberment Insurance will be effective under the same terms as set forth for Member Life Insurance in this Section B, Article 1. However, in no event will Member Accidental Death and Dismemberment Insurance be in force for a Member who is not insured for Member Life Insurance. Any change in a Member's Scheduled Benefit will be as stated in this Section B, Article 1. Article 3 - Dependent Life Insurance Dependent Life Insurance is available only with respect to Dependents of Members currently insured for Member Life Insurance. If a Member is eligible for Dependent Life Insurance, such insurance will be effective under the same terms as set forth for Member Life Insurance in this Section B, Article 1, except as described below. This policy has been updated effective January 1, 2014 PART III - INDIVIDUAL REQUIREMENTS AND RIGHTS GC 6007 Section B - Effective Dates, Page 5",
    'metadatas1': "{'Page_No.': 'Page 8', 'filing_name': 'Principal-Sample-Life-Insurance-Policy'}",
    'ids2': '61',
    'documents3': "f . claim requirements listed in PART IV, Section D, must be satisfied; and g. all medical evidence must be satisfactory to The Principal. Article 3 - Benefits Payable If all of the benefit qualifications are met, The Principal will pay: a. 100% of the Scheduled Benefit (or approved amount, if applicable) in force for loss of life; or b. 50% of the Scheduled Benefit (or approved amount, if applicable) in force if one hand is severed at or above the wrist; or c. 25% of the Scheduled Benefit (or approved amount, if applicable) in force for loss of thumb and index finger on the same hand; or d. 50% of the Scheduled Benefit (or approved amount, if applicable) in force if one foot is severed at or above the ankle; or e. 50% of the Scheduled Benefit (or approved amount, if applicable) in force if the sight of one eye is permanently lost (For this purpose, vision not correctable to better than 20/200 will be considered loss of sight.); or f. 100% of the Scheduled Benefit (or approved amount, if applicable) in force for more than one of the losses listed in b., d., or e. above. Total payment for all losses under this Article 3 that result from the same accident will not exceed the Scheduled Benefit (or approved amount, if applicable). Payment for loss of life will be to the beneficiary named for Member Life Insurance. Payment will be subject to the Beneficiary, Facility of Payment and Settlement of Proceeds provisions of PART IV, Section A. Payment for all other losses will be to the Member. Disappearance It will be presumed that a Member has lost his or her life if: a. the Member's body has not been found within 365 days after the disappearance of a conveyance in which the Member was an occupant at the time of disappearance; and b. the disappearance of the conveyance was due to its accidental wrecking or sinking; and c. this Group Policy would have covered the injury resulting from the accident. This policy has been updated effective January 1, 2014 PART IV - BENEFITS GC 6015 Section B - Member Accidental Death and Dismemberment Insurance, Page 2",
    'metadatas2': "{'Page_No.': 'Page 60', 'filing_name': 'Principal-Sample-Life-Insurance-Policy'}",
    'included3': 'a',
    'distances0': '0.28931906819343567',
    'included0': 'm',
    'distances4': '0.3220527470111847',
    'ids8': '46',
    'distances1': '0.31424590945243835',
    'metadatas3': "{'Page_No.': 'Page 54', 'filing_name': 'Principal-Sample-Life-Insurance-Policy'}",
    'metadatas5': "{'Page_No.': 'Page 32', 'filing_name': 'Principal-Sample-Life-Insurance-Policy'}",
    'ids6': '56',
    'documents9': "Section C - Dependent Life Insurance Article 1 - Schedule of Insurance Subject to the Effective Date provisions of PART III, Section B, the Scheduled Benefit for an insured Dependent will be based on the status of the Dependent: Class ALL MEMBERS Dependent *Scheduled Benefit Spouse $5,000 Children (age at death) 0 days old but less than 6 months $1,000 6 months and older $2,000 *The Scheduled Benefit is subject to the Proof of Good Health requirements as shown in PART III, Section B, Article 1. Because of the Proof of Good Health requirements, the amount of insurance approved by The Principal may be different than the Scheduled Benefit. If the approved amount of insurance is different than the Scheduled Benefit, the approved amount will apply. In no event will a Dependent's Scheduled Benefit be more than 50% of the Member's Scheduled Benefit amount. If a Member elects a Dependent Life benefit in excess of 50% of the Member's Scheduled Benefit amount, the Dependent will be given the highest amount available, not to exceed 50%. Article 2 - Death Benefits Payable If a Dependent dies while insured for Dependent Life Insurance under this Group Policy, The Principal will pay the Scheduled Benefit (or approved amount, if applicable) in force for that Dependent on the date of death. This policy has been updated effective January 1, 2014 PART IV - BENEFITS GC 6016 Section C - Dependent Life Insurance, Page 1",
    'ids7': '52',
    'included5': 'a',
    'metadatas0': "{'Page_No.': 'Page 47', 'filing_name': 'Principal-Sample-Life-Insurance-Policy'}",
    'included4': 'd',
    'ids5': '32',
    'ids4': '58',
    'distances3': '0.3209908604621887',
    'included7': 'a',
    'metadatas4': "{'Page_No.': 'Page 57', 'filing_name': 'Principal-Sample-Life-Insurance-Policy'}",
    'ids3': '55',
    'distances2': '0.3202136158943176',
    'distances6': '0.34317225217819214',
    'ids1': '7',
    'documents7': "Coverage During Disability will cease on the earliest of: (1) the date the Member's Total Disability ends; or (2) the date the Member fails to send The Principal any required proof of ADL Disability or Total Disability; or (3) the date the Member ceases to be under the regular care and attendance of a Physician; or (4) the date the Member fails to submit to a required Medical Examination or Evaluation; or (5) the date the Member attains age 70. g. Limitations No benefits will be paid for any disability that: (1) results from willful self-injury or self-destruction, while sane or insane; or (2) results from war or act of war; or (3) results from voluntary participation in an assault, felony, criminal activity, insurrection, or riot. Article 7 - Accelerated Benefits a. Accelerated Benefits Qualification To be qualified for an Accelerated Benefit payment, a Member must: (1) be Terminally Ill and insured for a Member Life Insurance benefit of at least $10,000; and (2) send a request for Accelerated Benefit payment to The Principal; and (3) provide proof satisfactory to The Principal that he or she is Terminally Ill. b. Proof of Terminal Illness Proof that a Member is Terminally Ill will consist of: (1) a statement from the Member's Physician; and (2) any other medical information that The Principal believes necessary to confirm the Member's status. c. Benefit Payable The Principal will pay a Member who is qualified for Accelerated Benefits whatever amount he or she requests; except that: This policy has been updated effective January 1, 2014 PART IV - BENEFITS GC 6013 Section A - Member Life Insurance, Page 6",
    'metadatas6': "{'filing_name': 'Principal-Sample-Life-Insurance-Policy', 'Page_No.': 'Page 55'}"}]],
 'distances': [[0.0]]}

### Working with Cross-Encoder Tranformers

In [ ]:
!pip install sentence_transformers

Requirement already satisfied: sentence_transformers in /usr/local/lib/python3.11/dist-packages (4.1.0)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.11/dist-packages (from sentence_transformers) (4.52.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from sentence_transformers) (4.67.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from sentence_transformers) (2.6.0+cu124)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.11/dist-packages (from sentence_transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.11/dist-packages (from sentence_transformers) (1.15.3)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.11/dist-packages (from sentence_transformers) (0.33.0)
Requirement already satisfied: Pillow in /usr/local/lib/python3.11/dist-packages (from sentence_transformers) (11.2.1)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.11/dist-packages (from sentence_transformers) (4.14.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence_transformers) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence_transformers) (2025.3.2)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence_transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence_transformers) (6.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence_transformers) (2.32.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.20.0->sentence_transformers) (1.1.5)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence_transformers) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence_transformers) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence_transformers) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence_transformers) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence_transformers) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence_transformers) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence_transformers) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence_transformers) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence_transformers) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence_transformers) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence_transformers) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence_transformers) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence_transformers) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence_transformers) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence_transformers) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence_transformers) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.11.0->sentence_transformers) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.11.0->sentence_transformers) (1.3.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence_transformers) (2.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence_transformers) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence_transformers) (0.21.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers<5.0.0,>=4.41.0->sentence_transformers) (0.5.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->sentence_transformers) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn->sentence_transformers) (3.6.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.11.0->sentence_transformers) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence_transformers) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence_transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence_transformers) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.20.0->sentence_transformers) (2025.6.15)

In [ ]:
from sentence_transformers import CrossEncoder, util

In [ ]:
cross_encoder = CrossEncoder('cross-encoder/ms-marco-MiniLM-L-6-v2')

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/794 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/132 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

In [ ]:
results_df.head()

,ids,documents,distances,metadatas
0,48,"M ember's death, the Death Benefits Payable ma...",0.289319,"{'Page_No.': 'Page 47', 'filing_name': 'Princi..."
1,7,Section A - Member Life Insurance Schedule of ...,0.314246,"{'Page_No.': 'Page 8', 'filing_name': 'Princip..."
2,61,I f a Dependent who was insured dies during th...,0.320214,"{'Page_No.': 'Page 60', 'filing_name': 'Princi..."
3,55,"f . claim requirements listed in PART IV, Sect...",0.320991,"{'Page_No.': 'Page 54', 'filing_name': 'Princi..."
4,58,% of Scheduled Covered Loss Benefit Loss of Sp...,0.322053,"{'Page_No.': 'Page 57', 'filing_name': 'Princi..."

In [ ]:
# Testing cross-endocder
# Input (query, response) pairs for each of the top 20 responses received from the semantic search to the cross encoder
# Generate the cross_encoder scores for these pairs

cross_inputs = [[query, response] for response in results_df['documents']]
cross_rerank_scores = cross_encoder.predict(cross_inputs)

In [ ]:
 #Store the rerank_scores in results_df
results_df['Reranked_scores'] = cross_rerank_scores

In [ ]:
# Return the top 3 results from semantic search
top_3_semantic = results_df.sort_values(by='distances')
top_3_semantic[:3]

,ids,documents,distances,metadatas,Reranked_scores
0,48,"M ember's death, the Death Benefits Payable ma...",0.289319,"{'Page_No.': 'Page 47', 'filing_name': 'Princi...",-1.901206
1,7,Section A - Member Life Insurance Schedule of ...,0.314246,"{'Page_No.': 'Page 8', 'filing_name': 'Princip...",-5.409644
2,61,I f a Dependent who was insured dies during th...,0.320214,"{'Page_No.': 'Page 60', 'filing_name': 'Princi...",-3.535415

In [ ]:
# Return the top 3 results after reranking

top_3_rerank = results_df.sort_values(by='Reranked_scores', ascending=False)
top_3_rerank[:3]
top_3_RAG = top_3_rerank[["documents", "metadatas"]][:3]

In [ ]:
top_3_RAG

,documents,metadatas
0,"M ember's death, the Death Benefits Payable ma...","{'Page_No.': 'Page 47', 'filing_name': 'Princi..."
2,I f a Dependent who was insured dies during th...,"{'Page_No.': 'Page 60', 'filing_name': 'Princi..."
1,Section A - Member Life Insurance Schedule of ...,"{'Page_No.': 'Page 8', 'filing_name': 'Princip..."

In [ ]:
top_3_RAG['documents'].iloc[0]

"M ember's death, the Death Benefits Payable may be withheld until additional information has been received or the trial has been held. If a Member who was insured dies within the 31-day individual purchase period described in PART III, Section F, The Principal will pay his or her beneficiary the individual policy amount, if any, the Member had the right to purchase. No payment will be made before The Principal receives Written proof of the Member's death. Article 3 - Beneficiary A beneficiary should be named at the time a Member applies or enrolls under this Group Policy. A Member may name or later change a named beneficiary by sending a Written request to The Principal. A change will not be effective until recorded by The Principal. Once recorded, the change will apply as of the date the request was Signed. If The Principal properly pays any benefit before a change request is received, that payment may not be contested. Further: a. The naming of a new beneficiary in an application for individual purchase under PART III, Section F, Article 1, will be treated as a beneficiary change request under this Group Policy. b. If a Member's terminated insurance is reinstated, his or her beneficiary will be as recorded on the date of termination. If a Member is insured under this Group Policy on its Date of Issue and this insurance replaces insurance in force on the day immediately before the Date of Issue, the beneficiary named in such replaced insurance and recorded by the Policyholder or The Principal will be the beneficiary under this Group Policy until a new beneficiary is named. Article 4 - Facility of Payment If any of the below occur, benefits will be paid as stated. All such payments will discharge The Principal to the full extent of those payments. a. If a beneficiary is found guilty of the Member's death, such beneficiary may be disqualified from receiving any benefit due. Payment may then be made to any contingent beneficiary or to the executor or administrator of the Member's estate. b. Any benefit due a beneficiary who dies before the Member's death will be paid in equal shares to the Member's surviving beneficiaries. This policy has been updated effective January 1, 2014 PART IV - BENEFITS GC 6013 Section A - Member Life Insurance, Page 2"

In [ ]:
retrieved = top_3_RAG['documents'].iloc[0]

In [ ]:
query

'Death benifits'

### Generative Search Using OpenAI

In [ ]:
messages = [
  {
    "role": "system",
    "content": (
      "You are a highly reliable and detail-oriented AI assistant trained to help users understand insurance-related information. "
      "Your primary role is to answer queries by strictly using the facts retrieved from official insurance documents, such as filing reports, policy summaries, or regulatory filings. "
      "Do not generate information beyond what is retrieved. If the information is not in the provided documents, clearly state that you cannot answer. "
      "Maintain a professional, clear, and informative tone at all times."
    )
  },
  {
    "role": "user",
    "content": (
      f"{query}\n\n"
      f"Use only the retrieved content from the Principal-Sample-Life-Insurance-Policy report:\n\n{retrieved}"
    )
  }
]

In [ ]:
client_ai = openai.OpenAI(api_key=api_key)
response = client_ai.chat.completions.create(
        model="gpt-3.5-turbo",
        messages=messages
      )
response.choices[0].message.content

"In the provided excerpt from the Principal-Sample-Life-Insurance-Policy report, the information related to Death Benefits is as follows:\n\n1. Death Benefits Payable:\n- In the event of a Member's death, the Death Benefits Payable may be withheld until additional information is received or the trial has been held.\n- If a Member who was insured dies within the 31-day individual purchase period, The Principal will pay the beneficiary the individual policy amount that the Member had the right to purchase.\n- No payment will be made until The Principal receives written proof of the Member's death.\n\n2. Beneficiary:\n- A beneficiary should be named at the time a Member applies or enrolls under the Group Policy.\n- A Member may name or change a beneficiary by sending a written request to The Principal.\n- The change will only be effective once recorded by The Principal, and it will apply as of the date the request was signed.\n- If a benefit is properly paid before a change request is received, that payment cannot be contested.\n- Naming a new beneficiary in an application for individual purchase will be treated as a beneficiary change request.\n- If a Member's terminated insurance is reinstated, their beneficiary will be as recorded on the termination date.\n\n3. Facility of Payment:\n- If a beneficiary is found guilty of the Member's death, they may be disqualified from receiving any benefit due, and the payment may be made to another party.\n- If a beneficiary dies before the Member, the benefit will be paid in equal shares to the Member's surviving beneficiaries.\n\nThese details outline the process and provisions related to Death Benefits and the designation of beneficiaries within the specified life insurance policy."

In [ ]:
print(response.choices[0].message.content)

In the provided excerpt from the Principal-Sample-Life-Insurance-Policy report, the information related to Death Benefits is as follows:

1. Death Benefits Payable:
- In the event of a Member's death, the Death Benefits Payable may be withheld until additional information is received or the trial has been held.
- If a Member who was insured dies within the 31-day individual purchase period, The Principal will pay the beneficiary the individual policy amount that the Member had the right to purchase.
- No payment will be made until The Principal receives written proof of the Member's death.

2. Beneficiary:
- A beneficiary should be named at the time a Member applies or enrolls under the Group Policy.
- A Member may name or change a beneficiary by sending a written request to The Principal.
- The change will only be effective once recorded by The Principal, and it will apply as of the date the request was signed.
- If a benefit is properly paid before a change request is received, that payment cannot be contested.
- Naming a new beneficiary in an application for individual purchase will be treated as a beneficiary change request.
- If a Member's terminated insurance is reinstated, their beneficiary will be as recorded on the termination date.

3. Facility of Payment:
- If a beneficiary is found guilty of the Member's death, they may be disqualified from receiving any benefit due, and the payment may be made to another party.
- If a beneficiary dies before the Member, the benefit will be paid in equal shares to the Member's surviving beneficiaries.

These details outline the process and provisions related to Death Benefits and the designation of beneficiaries within the specified life insurance policy.

### Final Fuction to Stich everything together

In [ ]:
def retrieve_and_generate(query,
                          main_collection=insurance_collection,
                          cache_collection=cache_collection,
                          embed_model=embedding_functions,
                          reranker_model=cross_encoder,
                          llm_client=client_ai,
                          k_main=10,
                          k_final=3,
                          threshold=0.2):
    """
    End-to-end RAG pipeline for insurance chatbot:
    1. Check cache.
    2. If not found or far, search main collection.
    3. Store result in cache if needed.
    4. Rerank results using cross-encoder.
    5. Generate answer using OpenAI GPT.
    """

    print(f"\n Query received: {query}")

    query_embedding = client_ai.embeddings.create(
    model="text-embedding-ada-002",
    input=[query]
    ).data[0].embedding

    # Step 2: Check cache
    cache_results = cache_collection.query(query_embeddings=[query_embedding], n_results=1)
    retrieved_from_cache = False

    if cache_results['distances'][0] and cache_results['distances'][0][0] < threshold:
        print("\n User Query Found in cache.")
        cache_results_dict = cache_results['metadatas'][0][0]
        documents = [v for k, v in cache_results_dict.items() if k.startswith('documents')]
        ids = [v for k, v in cache_results_dict.items() if k.startswith('ids')]
        distances = [v for k, v in cache_results_dict.items() if k.startswith('distances')]
        metadatas = [v for k, v in cache_results_dict.items() if k.startswith('metadatas')]
        results_df = pd.DataFrame({'IDs': ids, 'documents': documents, 'Distances': distances, 'Metadatas': metadatas})
        retrieved_from_cache = True
    else:
        print("\n User Query Not found in cache. Querying main collection...")
        results = main_collection.query(query_embeddings=[query_embedding], n_results=k_main)
        results_df = pd.DataFrame({
            'IDs': results['ids'][0],
            'documents': results['documents'][0],
            'Distances': results['distances'][0],
            'Metadatas': results['metadatas'][0]
        })

        # Add to cache
        keys, values = [], []
        for key, value in results.items():
            if key not in ['embedding', 'uris', 'data'] and value is not None:
                for i, item in enumerate(value[0]):
                    keys.append(f"{key}{i}")
                    values.append(str(item))
        cache_collection.add(
            documents=[query],
            ids=[query],
            metadatas=dict(zip(keys, values))
        )

    # Step 3: Rerank using cross-encoder
    print("\n Reranking top results...")
    cross_inputs = [[query, doc] for doc in results_df['documents']]
    cross_scores = reranker_model.predict(cross_inputs)
    reranked = sorted(zip(results_df['documents'], cross_scores), key=lambda x: x[1], reverse=True)
    top_docs = [doc for doc, _ in reranked[:k_final]]

    # Step 4: LLM prompt generation
    retrieved_text = "\n\n".join(top_docs)
    messages = [
        {
            "role": "system",
            "content": (
                "You are a highly reliable and detail-oriented AI assistant trained to help users understand insurance-related information. "
                "Your primary role is to answer queries by strictly using the facts retrieved from official insurance documents, such as filing reports, policy summaries, or regulatory filings. "
                "Do not generate information beyond what is retrieved. If the information is not in the provided documents, clearly state that you cannot answer. "
                "Maintain a professional, clear, and informative tone at all times."
            )
        },
        {
            "role": "user",
            "content": (
                f"{query}\n\n"
                f"Use only the retrieved content from the insurance policy report:\n\n{retrieved_text}"
            )
        }
    ]

    # Step 5: Generate answer
    try:
        response = llm_client.chat.completions.create(
            model="gpt-3.5-turbo",
            messages=messages
        )
        answer = response.choices[0].message.content
        print("\n Answer:\n", answer)
        return answer
    except Exception as e:
        print(f"\n Error generating response: {e}")
        return "\n Sorry, something went wrong while generating the response."

## Query

🔹 Query 1:
"What is the claim process for nominees of the policy?"

✅ Tests your system's ability to retrieve procedural content.

🔹 Query 2:
"Are there any exclusions or conditions under which the insurance benefits are not paid?"

✅ Useful to validate retrieval of exception clauses and fine print.

🔹 Query 3:
"How is the policy surrender value calculated, and when is it applicable?"

✅ Checks the pipeline's effectiveness in explaining financial terms from policy documents.

In [ ]:
query = input("💬 Enter your insurance-related query: ").strip()
print(f"\n🔍 Query received: {query}")
results_df.head(3)  # after retrieval, before reranking

💬 Enter your insurance-related query: What is the claim process for nominees of the policy?

🔍 Query received: What is the claim process for nominees of the policy?

,ids,documents,distances,metadatas,Reranked_scores
0,48,"M ember's death, the Death Benefits Payable ma...",0.289319,"{'Page_No.': 'Page 47', 'filing_name': 'Princi...",-1.901206
1,7,Section A - Member Life Insurance Schedule of ...,0.314246,"{'Page_No.': 'Page 8', 'filing_name': 'Princip...",-5.409644
2,61,I f a Dependent who was insured dies during th...,0.320214,"{'Page_No.': 'Page 60', 'filing_name': 'Princi...",-3.535415

In [ ]:
query = input("Enter your insurance-related query: ")
response = retrieve_and_generate(query)

Enter your insurance-related query: What is the claim process for nominees of the policy?

 Query received: What is the claim process for nominees of the policy?

 User Query Not found in cache. Querying main collection...

 Reranking top results...

 Answer:
 The claim process for nominees of the policy is as follows:

1. **Notice of Claim**: The nominee needs to provide written notice to The Principal within 20 days after the date of the loss for which the claim is being made. However, if notice is given as soon as reasonably possible, it will not invalidate or reduce any claim.

2. **Claim Forms**: The Principal will provide appropriate claim forms upon receiving notice of the claim. If the forms are not provided within 15 days, the person can submit written proof covering the occurrence, character, and extent of the loss within the specified time for filing proof of loss.

3. **Proof of Loss**: Written proof of loss must be sent to The Principal within 90 days after the date of the loss, including details such as the date, nature, and extent of the loss. Additional information may be requested, and failure to comply could result in the declination of the claim.

4. **Payment, Denial, and Review**: The Principal has up to 45 days from claim receipt to process it. Incomplete information could lead to a request for more details. The Principal will pay benefits sooner if complete proof of loss is provided. If the claim is not payable, a detailed explanation for denial will be provided.

5. **Appeal Process**: A claimant can request an appeal of a claim denial in writing to The Principal within 180 days of receiving the denial notice. The Principal will conduct a full and fair review, notify the claimant of the decision within 45 days after the appeal request, and may request additional information.

6. **Medical Examinations and Autopsy**: The Principal may require medical examinations or autopsies, which will be paid for by them if claimed by the member or dependent.

7. **Legal Action**: Legal action to recover benefits must not be initiated earlier than 90 days after filing the required proof of loss or later than three years after that filing.

8. **Time Limits**: Any time limits in the claim procedures will be adjusted as required by law.

It is important to refer to the official insurance documents for any specific details or additional requirements related to the claim process.

In [ ]:
query = input("💬 Enter your insurance-related query: ").strip()
print(f"\n🔍 Query received: {query}")
results_df.head(3)  # after retrieval, before reranking

💬 Enter your insurance-related query: Are there any exclusions or conditions under which the insurance benefits are not paid?

🔍 Query received: Are there any exclusions or conditions under which the insurance benefits are not paid?

,ids,documents,distances,metadatas,Reranked_scores
0,48,"M ember's death, the Death Benefits Payable ma...",0.289319,"{'Page_No.': 'Page 47', 'filing_name': 'Princi...",-1.901206
1,7,Section A - Member Life Insurance Schedule of ...,0.314246,"{'Page_No.': 'Page 8', 'filing_name': 'Princip...",-5.409644
2,61,I f a Dependent who was insured dies during th...,0.320214,"{'Page_No.': 'Page 60', 'filing_name': 'Princi...",-3.535415

In [ ]:
query = input("Enter your insurance-related query: ")
response = retrieve_and_generate(query)

Enter your insurance-related query: Are there any exclusions or conditions under which the insurance benefits are not paid?

 Query received: Are there any exclusions or conditions under which the insurance benefits are not paid?

 User Query Not found in cache. Querying main collection...

 Reranking top results...

 Answer:
 Based on the information provided in the insurance policy report, there are specific exclusions and conditions under which insurance benefits may not be paid. Here are some of the key points:

1. If a beneficiary is found guilty of the Member's death, they may be disqualified from receiving any benefit due. In such a case, payment may be made to a contingent beneficiary or to the executor or administrator of the Member's estate.

2. No benefits will be paid for any disability that results from willful self-injury or self-destruction, war or act of war, or voluntary participation in activities such as assault, felony, criminal activity, insurrection, or riot.

3. Coverage during disability will cease under certain circumstances, such as when the Member's Total Disability ends, failure to provide required proof of disability, failure to be under the care of a physician, or failure to undergo a required medical examination or evaluation.

It is important to refer to the specific terms and conditions outlined in the insurance policy for a comprehensive understanding of all exclusions and conditions that may apply.

In [ ]:
query = input("💬 Enter your insurance-related query: ").strip()
print(f"\n🔍 Query received: {query}")
results_df.head(3)  # after retrieval, before reranking

💬 Enter your insurance-related query: How is the policy surrender value calculated, and when is it applicable?

🔍 Query received: How is the policy surrender value calculated, and when is it applicable?

,ids,documents,distances,metadatas,Reranked_scores
0,48,"M ember's death, the Death Benefits Payable ma...",0.289319,"{'Page_No.': 'Page 47', 'filing_name': 'Princi...",-1.901206
1,7,Section A - Member Life Insurance Schedule of ...,0.314246,"{'Page_No.': 'Page 8', 'filing_name': 'Princip...",-5.409644
2,61,I f a Dependent who was insured dies during th...,0.320214,"{'Page_No.': 'Page 60', 'filing_name': 'Princi...",-3.535415

In [ ]:
query = input("Enter your insurance-related query: ")
response = retrieve_and_generate(query)

Enter your insurance-related query: How is the policy surrender value calculated, and when is it applicable?

 Query received: How is the policy surrender value calculated, and when is it applicable?

 User Query Not found in cache. Querying main collection...

 Reranking top results...

 Answer:
 The information provided in the insurance policy report does not specifically address how the policy surrender value is calculated or when it is applicable. As a result, I cannot provide details on the calculation or applicability of the policy surrender value based on the retrieved content. If you require specific details on this matter, I recommend contacting the insurance provider directly for accurate information regarding the policy surrender value.

In [ ]:
query = input("💬 Enter your insurance-related query: ").strip()
print(f"\n🔍 Query received: {query}")
results_df.head(3)  # after retrieval, before reranking

💬 Enter your insurance-related query: What are the eligibility criteria for dependent life insurance under this policy?

🔍 Query received: What are the eligibility criteria for dependent life insurance under this policy?

,ids,documents,distances,metadatas,Reranked_scores
0,48,"M ember's death, the Death Benefits Payable ma...",0.289319,"{'Page_No.': 'Page 47', 'filing_name': 'Princi...",-1.901206
1,7,Section A - Member Life Insurance Schedule of ...,0.314246,"{'Page_No.': 'Page 8', 'filing_name': 'Princip...",-5.409644
2,61,I f a Dependent who was insured dies during th...,0.320214,"{'Page_No.': 'Page 60', 'filing_name': 'Princi...",-3.535415

In [ ]:
query = input("Enter your insurance-related query: ")
response = retrieve_and_generate(query)

Enter your insurance-related query: What are the eligibility criteria for dependent life insurance under this policy?

 Query received: What are the eligibility criteria for dependent life insurance under this policy?

 User Query Not found in cache. Querying main collection...

 Reranking top results...

 Answer:
 The eligibility criteria for Dependent Life Insurance under this policy include the following:

1. A person will be eligible for Dependent Life Insurance on the latest of:
   a. The date the person is eligible for Member Life Insurance;
   b. The date the person first acquires a Dependent;
   c. The date the person enters a class for which Dependent Life Insurance is provided under this Group Policy;
   d. The date Dependent Life Insurance is added to this Group Policy.

2. If a Member's Dependent is employed and covered under group term life coverage by the Dependent's employer, the date such coverage terminates due to the Dependent no longer being eligible will be considered the date the Member first acquires that Dependent.

3. Premiums for Dependent Life Insurance will be based on the Dependent's age and the standard rate of The Principal for the policy form to be issued.

4. A Dependent can qualify for individual purchase of insurance under various circumstances as outlined in the policy document, including termination of Dependent Life Insurance due to certain events like divorce, termination of the Group Policy, or the Member's coverage during disability ending.

Please note that the document mentions that this policy has been updated effective January 1, 2014.

In [ ]:
query = input("💬 Enter your insurance-related query: ").strip()
print(f"\n🔍 Query received: {query}")
results_df.head(3)  # after retrieval, before reranking

💬 Enter your insurance-related query: Can a member convert their group life insurance to an individual policy after termination? What is the process?

🔍 Query received: Can a member convert their group life insurance to an individual policy after termination? What is the process?

,ids,documents,distances,metadatas,Reranked_scores
0,48,"M ember's death, the Death Benefits Payable ma...",0.289319,"{'Page_No.': 'Page 47', 'filing_name': 'Princi...",-1.901206
1,7,Section A - Member Life Insurance Schedule of ...,0.314246,"{'Page_No.': 'Page 8', 'filing_name': 'Princip...",-5.409644
2,61,I f a Dependent who was insured dies during th...,0.320214,"{'Page_No.': 'Page 60', 'filing_name': 'Princi...",-3.535415

In [ ]:
query = input("Enter your insurance-related query: ")
response = retrieve_and_generate(query)

Enter your insurance-related query: Can a member convert their group life insurance to an individual policy after termination? What is the process?

 Query received: Can a member convert their group life insurance to an individual policy after termination? What is the process?

 User Query Not found in cache. Querying main collection...

 Reranking top results...

 Answer:
 Yes, a member can convert their group life insurance to an individual policy under certain conditions as outlined in the insurance policy. Here is the process:

1. **Purchase Qualification**: The member will qualify for individual purchase if their insurance under the Group Policy terminates due to specific reasons listed below:
    - The member's total Life Insurance terminates because they end Active Work or are no longer in a class eligible for insurance.
    - After being continuously insured under the Group Policy for at least five years, the member's total Member Life Insurance terminates due to the Group Policy termination or amendment that excludes the member's insurance class.
    - The member's Coverage During Disability ends because Total Disability ends and they do not return to Active Work within 31 days.
    - The member's Accelerated Benefits Premium Waiver Period ceases, and they do not qualify for Coverage During Disability.

2. **Notification and Application**: Notice of the individual purchase right must be given to the member before the insurance under the Group Policy terminates or as soon as reasonably possible thereafter. The member must apply for individual purchase, and the first premium for the individual policy must be paid within 31 days after the date Member Life Insurance or Coverage During Disability terminates under the Group Policy.

3. **Individual Policy Amount**: The maximum amount of insurance that can be purchased through the individual policy will depend on the specific circumstances of termination as described in the policy.

4. **Type of Individual Policy**: The individual policy will be for life insurance only, and it will be based on one of the forms issued by the insurance company to persons in the risk class to which the member belongs on the individual policy's effective date.

It is essential for the member to review the complete policy details and terms to fully understand the conversion process and eligibility criteria for converting the group life insurance to an individual policy.